import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const baseUrl = "https://dev-app-api.abceed.com/";
const client = createClient<paths>({ baseUrl: baseUrl });

export const ApiBookAll = () => client.GET("/mock/book/all", { params: {} });
export type ResponseBookAll =
	paths["/mock/book/all"]["get"]["responses"][200]["content"]["application/json"];
