import createClient from "openapi-fetch";
import type { paths, components } from "./schema"; // generated by openapi-typescript

const baseUrl = "https://dev-app-api.abceed.com/";
const client = createClient<paths>({ baseUrl: baseUrl });
export const ApiBookAll = () => client.GET("/mock/book/all", { params: {} });

type schemas = components["schemas"];
export type ResponseBookAll = schemas["response_book_all"];
export type TopCategory = schemas["top_category"];
export type SubCategory = schemas["book"];
export type Book = schemas["book"];
