import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript
const baseUrl = "https://dev-app-api.abceed.com/";
const pathBookAll = "/mock/book/all";
const client = createClient<paths>({ baseUrl: baseUrl });
export const ApiBookAll = () => client.GET(pathBookAll, { params: {} });
