openapi: "3.1.0"

info:
  title: "mock"
  version: "1.0.0"

servers:
- url: https://dev-app-api.abceed.com/
  description: dev

paths:
  "/mock/book/all":
    get:
      summary: "bool all"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  top_category_list:
                    type: array
                    items:
                      type: object
                      properties:
                        id_top_category:
                          type: string
                          example: "_top"
                        is_focused:
                          type: boolean
                          example: false
                        name_category:
                          type: string
                          example: "すべて"
                        sub_category_list:
                          type: array
                          items:
                            type: object
                            properties:
                              id_category:
                                type: string
                                example: "_ranking"
                              is_ranking:
                                type: boolean
                                example: true
                              name_category:
                                type: string
                                example: "人気ランキング"
                              need_load_more:
                                type: boolean
                                example: true
                              book_list:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    author:
                                      type: string
                                      example: "TEX加藤"
                                    content_type:
                                      type: string
                                      example: "book"
                                    create_at:
                                      type: string
                                      format: date
                                      example: "2017-01-06"
                                    has_contents:
                                      type: integer
                                      example: 6
                                    has_purchased:
                                      type: boolean
                                      example: false
                                    id_book:
                                      type: string
                                      example: "tokyu_kinhure_new"
                                    img_url:
                                      type: string
                                      format: uri
                                      example: "https://d3grtcc7imzgqe.cloudfront.net/img/book_dev/tokyu_kinhure_new.jpg"
                                    is_unlimited:
                                      type: integer
                                      example: 1
                                    name_book:
                                      type: string
                                      example: "TOEIC L&R TEST 出る単特急 金のフレーズ"
                                    publisher:
                                      type: string
                                      example: "朝日新聞出版"